#+TITLE: How do Chromebooks stack up against Windows Ultrabooks?
#+AUTHOR: Nathan Mador-House
#+DATE: 2016-11-07
#+CATEGORY: Consumer
#+TAGS: Linux Windows Hardware Laptops Google Chromebook
#+DESCRIPTION: A quick overview on how Chromebooks fit into the laptop market, particularly in regards to the higher end models.
#+LANG: en
#+STATUS: published
#+STARTUP: showall

* Operating System

Though it may seem obvious, the most obvious and important distinction between a chromebook and a windows laptop is the operating system. Where ChromeOS is web-based, meaning that most of the information is stored online.

In addition to being a lightweight operating system, ChromeOS is loosely built off of the Linux kernel. This gives it much more flexibility if you don't want to be pigeon-holed by Windows. If you are a Linux user, you'll be happy to note that there are solutions in place to provide either improved Linux functionality [[https://github.com/dnschneid/crouton][Crouton]], or a full distro [[https://galliumos.org][GalliumOS]]. I personally have used GalliumOS, and while it's not perfect on every chromebook, it is an excellent project whose creators and contributors should be immensely proud. See my post [[https://www.musicnate.ca/chromebook-as-a-linux-ultrabook.html][Chromebook as an Ultrabook]] here for using linux primarily on a chromebook.

* Hardware

Chromebooks are the spiritual successor to the original netbooks, though they have come a long way since their inception. For anyone who doesn't know, back in 2007 the term netbook was introduced to classify a laptop that was small, light, and inexpensive. Keep in mind that though the name implies it, netbooks were not limited to network services, as they contained physical hard drives. These devices kickstarted the trend of decreasing functionality in return for portability and cheaper prices (such as removing the optical drive). However, the smaller form factor and cheap components (particularly the severely under-powered processors) resulted in performance that was generally inadequate for daily tasks.

When the tablet form factor becoming more and more popular, netbooks quickly fell out of favour. In comes the Chromebook, a combination of the netbook and network computer, utilizing the portability of the netbook and increased functionality of a network computer in an ever more connected world.

While a network computer lacked any hard drive at all, current chromebooks ship with a small solid state drive (ssd), usually 16GB or 32GB. Sometimes these the ssd is replaceable/decent quality, but frequently it uses permanent connection and is much slower than a traditional ssd.

At the same time, mobile processors from Intel, ARM, and MediaTek have mostly caught up to users needs. For every person who needs a video/photo editing work machine, there are many more who are simply looking for a device that will play movies, browse to facebook and a little bit of word processing and emails on the side. This is the niche in which Chromebooks lie, providing an easy to use cloud based solution that is 'good enough' for the majority.

The most recent batch of chromebook hardware is almost indistinguishable from their windows counterparts. For the top end this includes identical i3/i5/i7 processors, 8GB / 16GB, 1080p or higher resolution ips screens,
