#+TITLE: Google IO Summation
#+AUTHOR: Nathan Mador-House
#+DATE: 2016-05-23
#+CATEGORY: Tech News
#+TAGS: Google Tech
#+DESCRIPTION: Google IO included talk of Android N, Google Assistant, two new services Allo and Duo and much more.
#+LANG: en
#+STATUS: published

* Google I/O

  Google IO (Input/Output) is one of the major tech events that happen each year. 2016 marks the 10th anniversary of the presentation.
  While I expected more fanfare for the 10th (it certainly debuted with a high energy musical/video performance), it was a pleasure to see a somewhat relaxed and calmer keynote.

  Some companies host events like this for the press, others have booths at consumer events, but Google's audience at IO consists of press, consumers, and a large selection of developers.
  Having development experience is not mandatory to attend any of the lectures, but it certainly helps when discussing the intricate details of new APIs or programs.
  Even though my main programming language is Python, I know enough Java to follow along with the developer talks. These talks are a boon of tips and tricks to using some to the new APIs.


* Google Home Assistant
  Presenting the Google Assistant was Mario Querioz. Even though Google Assistant is a software implementation, the main implementation is with a device named Google Home.
  I have to say that when introduced, my mind leapt to a comparison with the old Microsoft Clippy.

  At the start of the segment Mr.Querioz alluded to other companies with similar products on the market. When revealed, it is obvious the Google Home device takes inspiration from the [Amazon Echo](http://www.amazon.com/Amazon-Echo-Bluetooth-Speaker-with-WiFi-Alexa/dp/B00X4WHP5E).
  The 'Home' features all the connectivity that you would expect, including most of the functionality inherent in a Chromecast.
  Much of the focus of this segment was on the improvements in Google's backend machine learning and AI.

* Allo & Duo

  Allo and Duo are two new complementary communication services, where Allo is text-based and Duo is for video calling, presented by Erik Kay.
  Why Google decided to add yet another messaging app to their suite instead of fixing their current selection is beyond me. The question is whether anything  was revealed besides basic text and chat functionality that we have seen from their earlier offerings (Messenger, Hangouts).
  To be honest, I was quite surprised by their 'headline' feature which they are calling 'Whisper/Shout'. To put it simply, it is just font scaling. Smaller text for whispering and larger for shouting, chosen with a slider.
  The other features introduced were much more interesting to me. Allo will be fully integrated with Google Assistant, including machine learning for picture recognition and smart reply.
  Finally, Allo will allow for 'Incognito' chat, enabling End-to-End encryption.

  Duo is the video application counterpart to Allo. Duo includes many of the features of Allo, such as End-to-End encryption. With Facebook video calling, Skype, and FaceTime crowding the market, it is interesting to see how Google is trying to differentiate Duo.
  Duo takes hints from its competitors, such as cross-platform availability from Skype and Facebook and phone number based identification from FaceTime.

* Android N(anaimo Bar)

  There are always so many new features in Android updates that it becomes hard to summarize all of the changes properly.
  The major areas of innovation are in Visual Layouts and Virtual Reality. In terms of layouts, N brings multitasking to a new level with split screen multi-windows.
  It also introduces Picture-in-Picture mode for Android TV, which apparently is not useful for tablets or phones. 
  Finally, Google has announced ['Daydream'](google-daydream.html), explained by Clay Bevor as a new platform for VR. The platform includes detailed specifications for software, new phone hardware, and a physical headset. What I found of particular interest was the inclusion of a headband, which has been a topic of debate for previous Google VR implementations (Cardboard).

* Conclusion

  Overall it was a keynote filled with some novel ideas, fake excitement, and a whole lot of 'pass the buck.' What was the star of Google IO so far? Undoubtedly the machine learning and AI teams behind all of the interesting tech. I look forward to writing about the rest of IO and hope there are more juicy tech stories to come.
