#+TITLE: Google Daydream
#+AUTHOR: Nathan Mador-House
#+DATE: 2016-06-03
#+CATEGORY: Tech News
#+TAGS: Google, Tech, Virtual Reality
#+DESCRIPTION: Daydream is Google's platform for mobile Virtual Reality.
#+LANG: en
#+STATUS: published

As of this writing, there are only a few major players in the virtual reality market. The market itself is split between mobile solutions like the Gear VR by Samsung and head mounted display such as the Vive by HTC/Valve, which have to be paired with a top-of-the-line gaming pc.
Google also joined the fray two years ago with their massively successful Cardboard project.

While details are still scarce about Daydream, it seems clear that it is the successor to Cardboard. Where Cardboard was simply an accessory that allows current smartphones to act as VR headsets, Daydream aims to guide the hardware specifications of new phones towards being more competent at VR.
Google has partnered with eight manufacturers (Samsung, HTC, LG, Xiaomi, Huawei, ZTE, Asus, and Alcatel) who will incorporate Daydream specifications into new phones.

Daydream is open to developers to start playing with now, but it probably won't be until the release of Android N that we see some real momentum.
